# Generated by Django 6.0 on 2025-12-17 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('business_hours_start', models.TimeField(default=datetime.time(8, 0))),
                ('business_hours_end', models.TimeField(default=datetime.time(17, 0))),
            ],
        ),
    ]
